# Generated by Django 2.2.1 on 2020-06-03 16:23

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('content_type', models.CharField(choices=[('MARKDOWN', 'MARKDOWN'), ('HTML', 'HTML'), ('LATEX', 'LATEX')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SolutionApproach',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description_content_type', models.CharField(choices=[('MARKDOWN', 'MARKDOWN'), ('HTML', 'HTML'), ('LATEX', 'LATEX')], max_length=100)),
                ('description_content', models.TextField()),
                ('complexity_analysis_content_type', models.CharField(choices=[('MARKDOWN', 'MARKDOWN'), ('HTML', 'HTML'), ('LATEX', 'LATEX')], max_length=100)),
                ('complexity_analysis_content', models.TextField()),
                ('question', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='content_management_portal.Question')),
            ],
        ),
        migrations.CreateModel(
            name='RoughSolution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField()),
                ('code_type', models.CharField(choices=[('PYTHON', 'PYTHON'), ('C', 'C'), ('CPP', 'CPP'), ('PYTHON36', 'PYTHON36'), ('PYTHON37', 'PYTHON37'), ('PYTHON38', 'PYTHON38'), ('PYTHON38_DATASCIENCE', 'PYTHON38_DATASCIENCE'), ('PYTHON38_AIML', 'PYTHON38_AIML')], max_length=20)),
                ('filename', models.CharField(max_length=100)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rough_solutions', to='content_management_portal.Question')),
            ],
        ),
        migrations.CreateModel(
            name='PrefilledCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField()),
                ('code_type', models.CharField(choices=[('PYTHON', 'PYTHON'), ('C', 'C'), ('CPP', 'CPP'), ('PYTHON36', 'PYTHON36'), ('PYTHON37', 'PYTHON37'), ('PYTHON38', 'PYTHON38'), ('PYTHON38_DATASCIENCE', 'PYTHON38_DATASCIENCE'), ('PYTHON38_AIML', 'PYTHON38_AIML')], max_length=20)),
                ('filename', models.CharField(max_length=100)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prefilled_codes', to='content_management_portal.Question')),
            ],
        ),
        migrations.CreateModel(
            name='Hint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content_type', models.CharField(choices=[('MARKDOWN', 'MARKDOWN'), ('HTML', 'HTML'), ('LATEX', 'LATEX')], max_length=100)),
                ('content', models.TextField()),
                ('order_id', models.IntegerField(default=1)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hints', to='content_management_portal.Question')),
            ],
        ),
        migrations.CreateModel(
            name='CleanSolution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField()),
                ('code_type', models.CharField(choices=[('PYTHON', 'PYTHON'), ('C', 'C'), ('CPP', 'CPP'), ('PYTHON36', 'PYTHON36'), ('PYTHON37', 'PYTHON37'), ('PYTHON38', 'PYTHON38'), ('PYTHON38_DATASCIENCE', 'PYTHON38_DATASCIENCE'), ('PYTHON38_AIML', 'PYTHON38_AIML')], max_length=20)),
                ('filename', models.CharField(max_length=100)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cleansolutions', to='content_management_portal.Question')),
            ],
        ),
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input', models.CharField(max_length=100)),
                ('output', models.CharField(max_length=100)),
                ('is_hidden', models.BooleanField()),
                ('score', models.IntegerField()),
                ('order_id', models.IntegerField(default=1)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testcases', to='content_management_portal.Question')),
            ],
        ),
    ]
