# Generated by Django 2.2.1 on 2020-06-03 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content_management_portal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_cases', to='content_management_portal.Question'),
        ),
        migrations.AlterField(
            model_name='cleansolution',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clean_solutions', to='content_management_portal.Question'),
        ),
        migrations.AlterField(
            model_name='solutionapproach',
            name='question',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='solution_approach', to='content_management_portal.Question'),
        ),
    ]
